### PR TITLE
Add MapBox location search

### PR DESCRIPTION
**Pull request by Carifio24**
This PR adds location search via MapBox and wires it up to the Leaflet map. I've deliberately refactored the MapBox functionality to live outside of the component; this will both allow us to easily use it across multiple components and will also help with bringing the core functionality upstream to `vue-toolkit` (which is on my to-do list).

### CODE REVIEW

**Comment by patudom** [comment]
The TEMPO field of regard includes Canada and Mexico (and Cuba, Bermuda, and maybe a touch of Haiti and the Dominican), so we should include those too. Once we have the shape file from the TEMPO team we may want to restrict search to within the field of regard, but let's not worry about that for now. (Even locations inside the field of regard could have no data because clouds, depending on the date range.)
Screenshot 2024-04-17 at 4 14 28 PM

**Comment by Carifio24** [comment]
@patudom I've updated to include the other countries inside the field of regard. Agreed that we can revisit what to include once we have s shapefile from the TEMPO team.

**Comment by patudom** [comment]
I don't know if this is just a css issue, but the dropdown with the location matches doesn't show up for me, so I can't test the "go to" functionality.
Screenshot 2024-04-17 at 7 08 45 PM

**Comment by Carifio24** [comment]
Do you have your `.env` file set up? If you don't, you won't get any results since the API key won't be in the request (you should be able to reuse the one from the solar eclipse story).

**Comment by Carifio24** [comment]
Just rebased to remove conflicts.

**Comment by patudom** [comment]
Yep, .env file was my issue. Thanks!

**Pull request merged**
